# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 839dbf733ecca78965b22fdf54d7eba9a10d82fc390ba09fd08c7803d98b76c9eb642796b09f761c32a9e5d14edfceeeae82fe608e1b147ff60229c024f68831

test:
  secret_key_base: 45dcc2cd1bae12e5e6c1007823d5ae2362dcd1c04b490f50e1240781df11e167b81f7ea49288fcdec15173cbf3427a1ab469823e56826c7e394137f8f81dcbf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
